mule:
  api_id: '20961314'

sf:
 client_id: '3MVG9WVXk15qiz1I2zDPPHvgTfsW_RMqrxu5cHT1s3ZiHtYE1xT03DbRO9cAXDRCz.qmEHLKJ12W9Q4EjUI1F' 
 client_secret: '![ZoscaV7VSjXqxjJPiNoQPs4ejGrauxZ/qXLcPHlu6hF7RAhUsoOc5Vid0GkWh+g7gIID5T0BuknR6DsuikAugoNFoTC16Or01QKKg9WuDvQ=]'
 domain: 'http://localhost:8081' 
 
 
