mule:
  api_id: '20961314'

sf:
 client_id: '3MVG9WVXk15qiz1I2zDPPHvgTfsW_RMqrxu5cHT1s3ZiHtYE1xT03DbRO9cAXDRCz.qmEHLKJ12W9Q4EjUI1F' 
 client_secret: '![45e52MfHwynPTuVy6s/ojh3YegIVvJlFbmZW4vn7HB3svQuncKd6qyo7iB8INteT4///4swYRPasSVq4Cq2U5CwAK2EBj+81HHSxsy72npk=]'
 domain: 'http://localhost:8081' 
 
 
